### ISSUE TITLE
Kevoree behind proxy server

### ISSUE THREAD

**Issue by tdalianis** [kevoree/kevoree-library#17]
Hi everyone,

I have a kevoree instance running on server of our internal network which is behind a proxy server.
When i access the instance from the editor using the internal ip, the kevoree model is shown at the editor, but when i am using the public domain name of the server i get the error "**_Unable to connect to ws://domainName:9000/_**". 
At the same time at the kevoree logs i get "**_ERROR: WSGroup "sync": io.undertow.websockets.core.WebSocketFrameCorruptedException: UT002015: Extensions not allowed but received rsv of 4_**" 

Have you made any tests involving a proxy server? Is there a configuration that can be done to resolve this issue?

Thank you for your time in advance.

**Comment by manuelleduc** [comment]
According to the answer of stuartwdouglas in this issue (https://github.com/Atmosphere/atmosphere/issues/1550) the problem might be fixed with Undertow 1.0.4.Final

Currently the WSGroup is dependent of Undertow 1.2.0 (as a recursive dependency of fr.braindead:wsmsgbroker-client:1.0.6

I'm going to test if I can update the version of undertow.

I'll let you know how it goes as soon as possible.

PS : Tomorrow is a public holiday in France (bastille day) so basically no one at INRIA will work neither tomorrow not on Friday.

**Comment by maxleiko** [comment]
Closing this as it is not really Kevoree-related.
