### ISSUE TITLE
Kevoree Maven Resolver

### ISSUE THREAD

**Issue by tdalianis** [kevoree/kevoree-library#18]
Kevoree v.5.3.1 doesn't seem to take into account the settings.xml of the local maven repository, so any parameters like proxy settings or private repository settings are ignored, causing an issue with the libraries.

**Comment by dukeboard** [comment]
True at the moment we only read the repository directory from this config file and not any network configuration. We can of course enhance the resolver to take this into account. In addition, one of our user had already a similar issue and used with success a global configuration of the JVM before the launch of Kevoree following parameters defined in the following page: http://docs.oracle.com/javase/6/docs/technotes/guides/net/proxies.html

Maybe try this and tell us if any troubles occurs with this method
Best regards,

**Comment by maxleiko** [comment]
@dukeboard  We do handle `settings.xml` now in 5.4.0-SNAPSHOT because I've switch from our custom maven resolver to Jboss ShrinkWrap Maven Resolver.  

But you cannot benefit from this new feature in 5.3.1. You must use 5.4.0-SNAPSHOT. Whether in changing the <kevoree.version> in your pom.xml properties or by specifying it on the command-line with `-Dkevoree.version=5.4.0-SNAPSHOT`

**Comment by maxleiko** [comment]
fixed in `5.4.0-SNAPSHOT`
